import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "@/auth/currentUser";
import Link from "next/link";
import LogOut from "./components/LogOut";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col p-8 antialiased items-center w-full h-screen max-w-5xl m-auto`}
      >
        <header className="w-full flex justify-end">
          {user == null ? (
            <div className="flex gap-4">
              <Link href="/sign-in" className="hover:underline">
                Sign In
              </Link>
              <Link href="/sign-up" className="">
                Sign Up
              </Link>
            </div>
          ) : (
            <>
              <LogOut />
            </>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
